language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
branches:
  except:
    - python3
install:
 - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
 - ~/.poetry/bin/poetry install -E dnssec -E doh -E idna -E trio -E curio
script:
 - ~/.poetry/bin/poetry run pytest --cov=. --cov-report=xml:coverage.xml
after_success:
 - bash <(curl -s https://codecov.io/bash)
