#! /bin/sh
set -eu

# Test outside the source tree to ensure to run against installed version.
cp -r tests "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"

for py3vers in $(py3versions -sv); do
    echo Testing with python$py3vers
    python$py3vers -m pytest -ra tests
done
